apiVersion: v1
kind: Service
metadata:
  name: {{ include "wdwtables.fullname" . }}-api
  labels:
{{ include "wdwtables.labels" . | indent 4 }}
{{ include "wdwtables.api.labels" . | indent 4}}
spec:
  type: {{ .Values.api.service.type }}
  publishNotReadyAddresses: true
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "wdwtables.name" . }}-api
    app.kubernetes.io/instance: {{ .Release.Name }}
status:
  loadBalancer: {}
